{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb
    port: {{ .Values.mongodb.service.port }}
    targetPort: {{ .Values.mongodb.service.port }}
  type: ClusterIP
{{- end }}