{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-sec
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.mongodb.auth.username | b64enc | quote }}
  password: {{ .Values.mongodb.auth.password | b64enc | quote }}
{{- end }}